<?php

use JetBrains\PhpStorm\Pure;

class Cylinder extends Circle
{
    public int $height;

    #[Pure] public function __construct(string $name, float|int $radius, int $height)
    {
        parent::__construct($name, $radius);
        $this->height = $height;
    }

    #[Pure] public function calculateArea(): int|float
    {
        return parent::calculateArea() * 2 + parent::calculatePerimeter() * $this->height ; // TODO: Change the autogenerated stub
    }

    #[Pure] public function calculateVolume(): int|float {
        return $this->calculateArea() * $this->height;
    }
}